/**
 * Notification mechanism for runtime-learned capability constraints.
 *
 * When an adapter discovers at runtime that a model rejects a parameter,
 * it builds a pre-filled GitHub New Issue URL and prints it via console.warn
 * once per modelId+capability per process. Users see the warning, can click
 * the URL, and submit a well-structured issue with model id + error message
 * + adapter version + SDK version already filled in.
 *
 * This is intentionally NOT telemetry: no automatic data exfiltration, no
 * phone-home endpoint, no opt-in flag. Maintainers see signal only when a
 * user takes an explicit action (clicking the URL). The pattern preserves
 * user privacy AND gives maintainers actionable signal when something new
 * shows up in the wild.
 */

/**
 * Inputs for the click-to-file warning + URL builder.
 *
 * Adapters populate this at the moment they learn a new constraint. The
 * `packageName` field is what appears as a label and in the title; it MUST
 * be the npm package name (e.g. `@llm-ports/adapter-anthropic`), not a
 * short alias.
 *
 * The `capability` field is the constraint name that was learned (e.g.
 * `temperatureLocked`, `jsonModeUnsupported`). Adapters can also pass
 * a free-form string for capabilities not in the standard `ModelCapabilities`
 * enum — the URL builder treats it as opaque.
 */
export interface FirstLearningEvent {
  /** Full npm package name, e.g. `@llm-ports/adapter-anthropic`. */
  packageName: string;
  /** Provider-side model id that exhibited the constraint, e.g. `claude-opus-4-5`. */
  modelId: string;
  /** Constraint name that was learned, e.g. `temperatureLocked`. */
  capability: string;
  /** The error message the provider returned (used to title the issue + verify). */
  providerErrorMessage: string;
  /** The installed adapter version, e.g. `0.1.0-alpha.3`. */
  adapterVersion: string;
  /** The installed SDK version (e.g. `@anthropic-ai/sdk` version). */
  sdkVersion: string;
  /**
   * Base URL of the project's GitHub repository. The URL builder appends
   * `/issues/new?title=...&body=...&labels=...` to this. Default in the
   * builder is `https://github.com/baabakk/llm-ports`.
   */
  repoUrl?: string;
}

/**
 * Build a pre-filled GitHub New Issue URL for a runtime-learned constraint.
 *
 * The URL opens GitHub's New Issue form with title, body, and labels already
 * populated from the event. The user reviews + edits + submits in seconds.
 *
 * Exported for testing and for adapters that want to surface the URL in a
 * non-console channel (logger, Sentry custom event, etc.). The default
 * caller is `emitFirstLearningWarning` below which prints the URL via
 * `console.warn`.
 */
export function buildLearningIssueUrl(event: FirstLearningEvent): string {
  const repoUrl = event.repoUrl ?? "https://github.com/baabakk/llm-ports";
  const title = `Add ${event.modelId} to ${event.capability} catalog (${event.packageName})`;
  const body = [
    "## Auto-generated by adapter runtime learning",
    "",
    `**Model:** \`${event.modelId}\``,
    `**Constraint learned at runtime:** \`${event.capability}\``,
    `**Provider error message:** \`${event.providerErrorMessage}\``,
    "",
    "**Versions:**",
    `- \`${event.packageName}\` v${event.adapterVersion}`,
    `- SDK v${event.sdkVersion}`,
    typeof process !== "undefined" ? `- Node.js ${process.version}` : "",
    "",
    "The adapter learned this constraint at runtime and stripped the parameter",
    "from subsequent calls automatically. Filing this issue lets us add the",
    "model to the static catalog so other users skip the discovery round-trip.",
    "",
    "(Auto-prefilled. Please review and edit before submitting if anything",
    "looks wrong, especially the model ID.)",
  ]
    .filter((line) => line !== "")
    .join("\n");

  // Determine sensible labels. The package-specific area label (e.g.
  // `area:adapter-anthropic`) is added when we can derive it from the
  // package name.
  const labels = ["bug", "runtime-learned"];
  const areaLabel = derivePackageAreaLabel(event.packageName);
  if (areaLabel) labels.push(areaLabel);

  return (
    `${repoUrl}/issues/new?` +
    `title=${encodeURIComponent(title)}&` +
    `body=${encodeURIComponent(body)}&` +
    `labels=${encodeURIComponent(labels.join(","))}`
  );
}

/**
 * Per-process tracking of which (modelId, capability) pairs we've already
 * warned about. Ensures the console.warn fires once per pair per process,
 * not on every call.
 */
const warnedAlready = new Set<string>();

/**
 * Emit a `console.warn` with the click-to-file URL for a runtime-learned
 * constraint. Fires exactly once per (modelId, capability) pair per process.
 *
 * Adapters call this from inside their `rememberConstraint`-equivalent path
 * the first time a specific constraint is learned. Subsequent calls to
 * `remember` the same constraint stay silent (the adapter's retry loop
 * still operates normally; only the warning is gated).
 */
export function emitFirstLearningWarning(event: FirstLearningEvent): void {
  const key = `${event.modelId}::${event.capability}`;
  if (warnedAlready.has(key)) return;
  warnedAlready.add(key);

  const url = buildLearningIssueUrl(event);
  // Use the simplest form of console.warn to maximize compatibility with
  // common log shippers (Vercel, Cloudflare Workers, AWS Lambda, etc.).
  console.warn(
    `[${event.packageName}] Model "${event.modelId}" rejected ${event.capability}. ` +
      `Stripped for subsequent calls in this process.\n\n` +
      `Help us improve the static catalog (one click, pre-filled): ${url}`,
  );
}

/** Test-only: reset the per-process warning state. */
export function _resetWarnedState(): void {
  warnedAlready.clear();
}

/**
 * Derive a sensible `area:adapter-<name>` label from a package name like
 * `@llm-ports/adapter-anthropic`. Returns null for packages outside that
 * pattern.
 */
function derivePackageAreaLabel(packageName: string): string | null {
  const match = /^@llm-ports\/adapter-([a-z0-9-]+)$/i.exec(packageName);
  if (!match) return null;
  return `area:adapter-${match[1]}`;
}
